name: LibreSSL

on: [push, pull_request]

permissions:
  contents: read

jobs:
  libressl:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Install dependencies
        run: apk add binutils --no-cache build-base git readline-dev libressl-dev ncurses-dev git cmake zlib-dev libsodium-dev gnu-libiconv

      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Configure
        run: ./configure

      - name: Make
        run: make -j $(nproc)  -C build

      - name: Test
        run: |
          .ci/memory-leak-test.sh
          .ci/vpntools-check.sh
